# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'windows-latest'

steps:
- task: HugoTask@1
  inputs:
    source: '$(Build.SourcesDirectory)'
    destination: '$(Build.SourcesDirectory)\public\updated'
    baseURL: 'https://www.sigmact.com/updated/'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\public\updated'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureCLI@2
  displayName: 'Delete Prod'
  inputs:
    azureSubscription: "シグマコンサルティング(eee9046c-f7c0-4e03-98e0-3660ae9224fc)"
    scriptType: "ps"
    scriptLocation: "inlineScript"
    inlineScript: 'az storage blob delete-batch -s $(container) --pattern * --account-name $(storagename) --account-key $(accountkey)'

- task: AzureCLI@2
  displayName: 'Upload Prod'
  inputs:
    azureSubscription: "シグマコンサルティング(eee9046c-f7c0-4e03-98e0-3660ae9224fc)"
    scriptType: "ps"
    scriptLocation: "inlineScript"
    inlineScript: 'az storage blob upload-batch -d $(container) -s $(Build.SourcesDirectory)\public --account-name $(storagename) --account-key $(accountkey)'
